# DO NOT EDIT THIS FILE!! 
# IF MODIFIED IN ANY WAY, YOU WILL RECEIVE 0 FOR THE GRADE!

import unittest
from Assignment1 import *

# Test case for built_in_functions_max() function
def test_built_in_functions_max():
    assert built_in_functions_max(3, 5, 2) == 5  # max = 5
    assert built_in_functions_max(-1, -2, -3) == -1 # max = -1

# Test case for built_in_functions_min() function
def test_built_in_functions_min():
    assert built_in_functions_min(3, 5, 2) == 2  # min = 2
    assert built_in_functions_min(-1, -2, -3) == -3 # min = -3
    
# Test case for check_number() function
def test_check_number():
    assert check_number(5) == "Positive"
    assert check_number(-5) == "Negative"
    assert check_number(0) == "Zero"
    
# Test case for star_shape() function
def test_star_shape():
    assert star_shape(5) == "*\n**\n***\n****\n*****"
    assert star_shape(3) == "*\n**\n***"

# Test case for count_multiples_of_3() function
def test_count_multiples_of_3():
    assert count_multiples_of_3(11) == "1\n2\nMultiple of 3\n4\n5\nMultiple of 3\n7\n8\nMultiple of 3\n10\n11"
    assert count_multiples_of_3(20) == "1\n2\nMultiple of 3\n4\n5\nMultiple of 3\n7\n8\nMultiple of 3\n10\n11\nMultiple of 3\n13\n14\nMultiple of 3\n16\n17\nMultiple of 3\n19\n20"
# Test case for sum_of_even_numbers() function
def test_sum_of_even_numbers():
    assert sum_of_even_numbers(1, 10) == 30  # Even numbers: 2, 4, 6, 8, 10; sum = 30
    assert sum_of_even_numbers(5, 15) == 50  # Even numbers: 6, 8, 10, 12, 14; sum = 50
    assert sum_of_even_numbers(1, 1) == 0  # No even numbers in this range
        
    
if __name__ == '__main__':
    unittest.main()
